In [2]:
!pip install Faker

Collecting Faker
  Downloading https://files.pythonhosted.org/packages/e4/be/d03e305f1d879f541c23d586023ec11b124d6cc3d75a95159470754134d9/Faker-8.10.0-py3-none-any.whl (1.2MB)
     |████████████████████████████████| 1.2MB 12.8MB/s
Requirement already satisfied: text-unidecode==1.3 in /usr/local/lib/python3.7/dist-packages (from Faker) (1.3)
Requirement already satisfied: python-dateutil>=2.4 in /usr/local/lib/python3.7/dist-packages (from Faker) (2.8.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.4->Faker) (1.15.0)
Installing collected packages: Faker
Successfully installed Faker-8.10.0

In [32]:
#importing packages
from faker import  Faker
from collections import namedtuple  
import datetime
from datetime import date 
from decimal import Decimal
import numpy as np
import statistics
import random


fake = Faker()
fake.profile()

{'address': '963 Sanders Courts\nNorth Michelle, AL 15039',
 'birthdate': datetime.date(1945, 9, 8),
 'blood_group': 'AB+',
 'company': 'Brooks, Thomas and Lee',
 'current_location': (Decimal('-14.410910'), Decimal('93.648207')),
 'job': 'Librarian, academic',
 'mail': 'vconley@yahoo.com',
 'name': 'Janet Martin',
 'residence': '66206 Rivera Walk\nBondstad, ID 66137',
 'sex': 'F',
 'ssn': '878-93-8592',
 'username': 'kathy71',
 'website': ['https://www.bennett.com/',
  'http://www.hampton-carlson.biz/',
  'http://jarvis.com/',
  'https://roth.info/']}

In [14]:
def get_named_tuple(population):
    '''
    This function generates list of fake person details.
    Attributes : 'name','blood_type','current_location','DOB'
    '''
    profile =  fake.profile()
    info_list = []
    person = namedtuple('person',['name','blood_type','current_location','DOB']) 
    for i in range(population):
        p = person(profile['name'],profile['blood_group'],profile['current_location'],profile['birthdate'])
        info_list.append(p)
    return info_list


# get_named_tuple(10000)

In [21]:
def calculateAge(birthDate): 
    '''
    This functions returns the age as we input the date of birth of the person
    '''
    today = date.today() 
    current_age = today.year - birthDate.year - ((today.month, today.day) < (birthDate.month, birthDate.day)) 
    return current_age

In [25]:
birth_date = datetime.date(1941,5,9)
birth_date.month
current_Age = calculateAge(birth_date)
print(current_Age)

80

In [30]:
def named_tuple_calculator(population):
    '''
    This function calculates and returns the largest blood type, mean-current_location,
     oldest_person_age ,average age and time taken for calculation using named tuple also it calls 
     the get_named_tuple and calulateAge functions.
    '''
    t0 = datetime.datetime.now()
    named_tuple_list = get_named_tuple(population)
    current_lan = []
    current_lon = []
    age = []
    blood_group = []
    for i in named_tuple_list:
        current_lan.append(i.current_location[0])
        current_lon.append(i.current_location[1])
        age.append(calculateAge(i.DOB))
        blood_group.append(i.blood_type)

    try:
        largest_blood_type = statistics.mode(blood_group)
    except:
        largest_blood_type = statistics.multimode(blood_group)

    mean_location = (np.mean(current_lan),np.mean(current_lon))
    maximum_age = np.max(age)
    average_age = np.mean(age)

    results = largest_blood_type,mean_location,maximum_age,average_age

    t1 = datetime.datetime.now()
    time_elapsed = (t1-t0).total_seconds()

    return results , time_elapsed 


data = named_tuple_calculator(100)

In [36]:
def get_dict_list(population) :
    info_list = []
    for i in range(population):
        profile =  fake.profile()
        d = {'name':profile['name'],"blood_type":profile['blood_group'],"current_location":profile['current_location'],
            "DOB": profile['birthdate']}
        info_list.append(d)
    return info_list

In [37]:
def dict_cal(population):
    '''
    This function calculates and returns the
    largest blood type, mean-current_location,
    oldest_person_age ,average age and time taken for calculation using Dictionary.
    '''
    t2 = datetime.datetime.now()
    dict_list = get_dict_list(population)
    lan = [] 
    lon = []
    age = []
    blood_group = []

    for i in dict_list:
        lan.append(i['current_location'][0])
        lon.append(i['current_location'][1])
        age.append(calculateAge(i['DOB']))
        blood_group.append(i['blood_type'])

    try:
        largest_blood_type = statistics.mode(blood_group)
    except:
        largest_blood_type = statistics.multimode(blood_group)

    mean_location = (np.mean(lan),np.mean(lon))
    maximum_age = np.max(age)
    average_age = np.mean(age)
    result = largest_blood_type,mean_location,maximum_age,average_age
    t3 = datetime.datetime.now()
    time_elapsed = (t3-t2).total_seconds()

    return result,time_elapsed ,dict_list

test = dict_cal(100)

In [38]:
test

(('A+', (Decimal('-5.45853153'), Decimal('17.54905543')), 114, 53.5),
 0.128906,
 [{'DOB': datetime.date(1987, 7, 21),
   'blood_type': 'O+',
   'current_location': (Decimal('41.492126'), Decimal('-52.741699')),
   'name': 'John Cox'},
  {'DOB': datetime.date(1941, 12, 13),
   'blood_type': 'B-',
   'current_location': (Decimal('41.417414'), Decimal('-56.654096')),
   'name': 'Mr. Kevin Burton MD'},
  {'DOB': datetime.date(1952, 12, 12),
   'blood_type': 'A+',
   'current_location': (Decimal('-0.929640'), Decimal('-33.499791')),
   'name': 'Teresa Small'},
  {'DOB': datetime.date(1906, 9, 2),
   'blood_type': 'O-',
   'current_location': (Decimal('53.9177895'), Decimal('82.756289')),
   'name': 'Vernon Stone'},
  {'DOB': datetime.date(1976, 9, 13),
   'blood_type': 'A+',
   'current_location': (Decimal('30.6883075'), Decimal('-97.646608')),
   'name': 'Susan Fernandez'},
  {'DOB': datetime.date(2019, 11, 29),
   'blood_type': 'A+',
   'current_location': (Decimal('11.9065665'), Decimal('-80.389149')),
   'name': 'Jessica Cook'},
  {'DOB': datetime.date(1935, 11, 6),
   'blood_type': 'AB-',
   'current_location': (Decimal('50.914465'), Decimal('108.286345')),
   'name': 'David Decker'},
  {'DOB': datetime.date(1965, 4, 18),
   'blood_type': 'A-',
   'current_location': (Decimal('-49.704391'), Decimal('123.422155')),
   'name': 'John Coleman'},
  {'DOB': datetime.date(2017, 9, 13),
   'blood_type': 'B+',
   'current_location': (Decimal('-53.158387'), Decimal('99.616725')),
   'name': 'Juan Carr'},
  {'DOB': datetime.date(2020, 11, 22),
   'blood_type': 'O-',
   'current_location': (Decimal('-49.9745545'), Decimal('-89.931963')),
   'name': 'Sara Martin DDS'},
  {'DOB': datetime.date(2000, 5, 8),
   'blood_type': 'B-',
   'current_location': (Decimal('31.458502'), Decimal('50.998836')),
   'name': 'Holly Coleman'},
  {'DOB': datetime.date(1930, 12, 8),
   'blood_type': 'B-',
   'current_location': (Decimal('74.811096'), Decimal('158.797675')),
   'name': 'Angela Hopkins'},
  {'DOB': datetime.date(1920, 5, 29),
   'blood_type': 'A+',
   'current_location': (Decimal('-41.0537865'), Decimal('-63.546755')),
   'name': 'Mr. Willie Ruiz PhD'},
  {'DOB': datetime.date(1965, 11, 8),
   'blood_type': 'AB-',
   'current_location': (Decimal('34.0183835'), Decimal('-172.715215')),
   'name': 'Heather Davis'},
  {'DOB': datetime.date(1929, 3, 6),
   'blood_type': 'B+',
   'current_location': (Decimal('86.395672'), Decimal('10.594647')),
   'name': 'Gregory Curry'},
  {'DOB': datetime.date(1937, 9, 1),
   'blood_type': 'O+',
   'current_location': (Decimal('47.6885745'), Decimal('147.997059')),
   'name': 'Tina Macdonald'},
  {'DOB': datetime.date(1936, 7, 13),
   'blood_type': 'A-',
   'current_location': (Decimal('-83.281310'), Decimal('169.734220')),
   'name': 'Mercedes Boyer'},
  {'DOB': datetime.date(2006, 7, 27),
   'blood_type': 'AB+',
   'current_location': (Decimal('7.529959'), Decimal('105.134387')),
   'name': 'Phillip Fitzgerald'},
  {'DOB': datetime.date(1910, 4, 13),
   'blood_type': 'B-',
   'current_location': (Decimal('53.2634005'), Decimal('130.550406')),
   'name': 'Victor Norris'},
  {'DOB': datetime.date(2019, 4, 22),
   'blood_type': 'AB-',
   'current_location': (Decimal('28.034626'), Decimal('149.491688')),
   'name': 'Laurie Love'},
  {'DOB': datetime.date(2017, 4, 9),
   'blood_type': 'O-',
   'current_location': (Decimal('-14.8868045'), Decimal('71.730860')),
   'name': 'Paul Harrell'},
  {'DOB': datetime.date(1946, 3, 1),
   'blood_type': 'B+',
   'current_location': (Decimal('27.6323925'), Decimal('34.326219')),
   'name': 'Abigail Hernandez'},
  {'DOB': datetime.date(2005, 4, 30),
   'blood_type': 'A+',
   'current_location': (Decimal('-52.935382'), Decimal('-145.219798')),
   'name': 'Amber Rowe'},
  {'DOB': datetime.date(1966, 12, 11),
   'blood_type': 'A+',
   'current_location': (Decimal('47.423639'), Decimal('105.372351')),
   'name': 'Margaret Zimmerman'},
  {'DOB': datetime.date(1910, 2, 10),
   'blood_type': 'AB+',
   'current_location': (Decimal('13.1424715'), Decimal('153.208841')),
   'name': 'Kathleen Brady'},
  {'DOB': datetime.date(1967, 11, 13),
   'blood_type': 'AB+',
   'current_location': (Decimal('21.2992545'), Decimal('133.442197')),
   'name': 'Brett Williams'},
  {'DOB': datetime.date(1943, 1, 3),
   'blood_type': 'A+',
   'current_location': (Decimal('57.9239625'), Decimal('-9.446795')),
   'name': 'Mrs. Yvonne Williams'},
  {'DOB': datetime.date(1995, 5, 21),
   'blood_type': 'O+',
   'current_location': (Decimal('26.058238'), Decimal('-84.745328')),
   'name': 'Angelica Mccall'},
  {'DOB': datetime.date(1954, 2, 12),
   'blood_type': 'AB-',
   'current_location': (Decimal('72.3787485'), Decimal('95.151839')),
   'name': 'Anna Richards'},
  {'DOB': datetime.date(1937, 9, 18),
   'blood_type': 'AB+',
   'current_location': (Decimal('-51.6601955'), Decimal('-152.353642')),
   'name': 'Benjamin Greene'},
  {'DOB': datetime.date(1911, 11, 16),
   'blood_type': 'A+',
   'current_location': (Decimal('0.3358445'), Decimal('-6.081378')),
   'name': 'Jill Lawrence'},
  {'DOB': datetime.date(1973, 12, 30),
   'blood_type': 'B-',
   'current_location': (Decimal('-87.1973335'), Decimal('102.252738')),
   'name': 'David Butler'},
  {'DOB': datetime.date(1938, 5, 16),
   'blood_type': 'O-',
   'current_location': (Decimal('-19.656962'), Decimal('72.583915')),
   'name': 'Thomas Shaffer'},
  {'DOB': datetime.date(1976, 8, 16),
   'blood_type': 'O+',
   'current_location': (Decimal('39.524314'), Decimal('-35.567768')),
   'name': 'Trevor Bean'},
  {'DOB': datetime.date(1936, 10, 2),
   'blood_type': 'A-',
   'current_location': (Decimal('40.9008325'), Decimal('54.531426')),
   'name': 'Timothy Matthews'},
  {'DOB': datetime.date(1944, 7, 19),
   'blood_type': 'A-',
   'current_location': (Decimal('-86.170970'), Decimal('42.263066')),
   'name': 'Angela Brown'},
  {'DOB': datetime.date(1938, 4, 19),
   'blood_type': 'A-',
   'current_location': (Decimal('80.0463375'), Decimal('-23.402628')),
   'name': 'Amanda Hall'},
  {'DOB': datetime.date(2012, 7, 18),
   'blood_type': 'O-',
   'current_location': (Decimal('64.1285875'), Decimal('88.208164')),
   'name': 'Robin Barrett'},
  {'DOB': datetime.date(1959, 6, 5),
   'blood_type': 'A-',
   'current_location': (Decimal('21.9735535'), Decimal('168.792460')),
   'name': 'Andrew Gonzalez'},
  {'DOB': datetime.date(1944, 12, 29),
   'blood_type': 'B-',
   'current_location': (Decimal('-19.581482'), Decimal('-9.683648')),
   'name': 'Elijah Roberts'},
  {'DOB': datetime.date(2006, 8, 26),
   'blood_type': 'O+',
   'current_location': (Decimal('-10.2182815'), Decimal('-84.226409')),
   'name': 'Carla Griffin'},
  {'DOB': datetime.date(1969, 10, 22),
   'blood_type': 'A-',
   'current_location': (Decimal('-37.2605295'), Decimal('119.697653')),
   'name': 'Robert Lane'},
  {'DOB': datetime.date(1975, 1, 5),
   'blood_type': 'A+',
   'current_location': (Decimal('-53.124160'), Decimal('-69.549710')),
   'name': 'Nathan Howard'},
  {'DOB': datetime.date(1918, 4, 10),
   'blood_type': 'O+',
   'current_location': (Decimal('-14.1324955'), Decimal('-159.859891')),
   'name': 'Samantha Ruiz'},
  {'DOB': datetime.date(2020, 3, 1),
   'blood_type': 'B-',
   'current_location': (Decimal('27.221476'), Decimal('83.564522')),
   'name': 'Wendy Thornton MD'},
  {'DOB': datetime.date(1932, 5, 10),
   'blood_type': 'B+',
   'current_location': (Decimal('52.570461'), Decimal('-17.414522')),
   'name': 'Hannah Fisher'},
  {'DOB': datetime.date(1997, 11, 21),
   'blood_type': 'B+',
   'current_location': (Decimal('58.803510'), Decimal('-45.481350')),
   'name': 'Kristina Wagner'},
  {'DOB': datetime.date(1977, 6, 29),
   'blood_type': 'AB-',
   'current_location': (Decimal('-61.469675'), Decimal('-107.435560')),
   'name': 'Rachael Knight'},
  {'DOB': datetime.date(1926, 4, 10),
   'blood_type': 'B-',
   'current_location': (Decimal('51.141923'), Decimal('-29.799743')),
   'name': 'Jordan Cook'},
  {'DOB': datetime.date(2001, 12, 1),
   'blood_type': 'O+',
   'current_location': (Decimal('-73.5427365'), Decimal('-91.962357')),
   'name': 'Michelle Ramos'},
  {'DOB': datetime.date(1932, 11, 30),
   'blood_type': 'B+',
   'current_location': (Decimal('-46.897303'), Decimal('135.536071')),
   'name': 'Paul Morris'},
  {'DOB': datetime.date(1985, 12, 8),
   'blood_type': 'A-',
   'current_location': (Decimal('-7.820458'), Decimal('15.948210')),
   'name': 'Colton Roman'},
  {'DOB': datetime.date(1933, 11, 27),
   'blood_type': 'O+',
   'current_location': (Decimal('36.2339085'), Decimal('139.205493')),
   'name': 'Brian Hughes'},
  {'DOB': datetime.date(1981, 10, 21),
   'blood_type': 'AB+',
   'current_location': (Decimal('-81.532328'), Decimal('121.236663')),
   'name': 'Denise Sanchez'},
  {'DOB': datetime.date(2008, 3, 17),
   'blood_type': 'A-',
   'current_location': (Decimal('-21.271921'), Decimal('-76.367686')),
   'name': 'Rachel Gonzalez'},
  {'DOB': datetime.date(1919, 3, 6),
   'blood_type': 'A+',
   'current_location': (Decimal('-15.4800505'), Decimal('0.781093')),
   'name': 'Gregory Miller'},
  {'DOB': datetime.date(1965, 11, 24),
   'blood_type': 'B-',
   'current_location': (Decimal('40.687213'), Decimal('105.201053')),
   'name': 'Linda Khan'},
  {'DOB': datetime.date(1961, 1, 21),
   'blood_type': 'A-',
   'current_location': (Decimal('28.447782'), Decimal('20.234090')),
   'name': 'Brian Morrison'},
  {'DOB': datetime.date(1968, 11, 13),
   'blood_type': 'O+',
   'current_location': (Decimal('-6.220071'), Decimal('-145.755835')),
   'name': 'Leslie Nunez'},
  {'DOB': datetime.date(2021, 4, 5),
   'blood_type': 'O+',
   'current_location': (Decimal('53.9140705'), Decimal('173.112306')),
   'name': 'Joyce Collins'},
  {'DOB': datetime.date(2012, 10, 4),
   'blood_type': 'O+',
   'current_location': (Decimal('-63.424060'), Decimal('-39.452608')),
   'name': 'Melissa Stewart'},
  {'DOB': datetime.date(1960, 11, 29),
   'blood_type': 'B+',
   'current_location': (Decimal('-30.4832815'), Decimal('-114.445418')),
   'name': 'Kimberly Burton'},
  {'DOB': datetime.date(1980, 3, 28),
   'blood_type': 'B-',
   'current_location': (Decimal('40.1608645'), Decimal('68.664691')),
   'name': 'Daniel Castillo'},
  {'DOB': datetime.date(1983, 11, 19),
   'blood_type': 'O-',
   'current_location': (Decimal('-12.8402435'), Decimal('-43.584882')),
   'name': 'Michael Aguilar'},
  {'DOB': datetime.date(1924, 5, 20),
   'blood_type': 'AB+',
   'current_location': (Decimal('-28.7170495'), Decimal('-109.030874')),
   'name': 'Amber Wilson'},
  {'DOB': datetime.date(1907, 1, 29),
   'blood_type': 'AB+',
   'current_location': (Decimal('21.7051235'), Decimal('-73.625794')),
   'name': 'Kayla Hernandez'},
  {'DOB': datetime.date(1963, 11, 22),
   'blood_type': 'B-',
   'current_location': (Decimal('8.0234485'), Decimal('146.236163')),
   'name': 'Veronica Smith'},
  {'DOB': datetime.date(1942, 10, 18),
   'blood_type': 'A+',
   'current_location': (Decimal('-36.0340735'), Decimal('87.605826')),
   'name': 'Christine Green'},
  {'DOB': datetime.date(1946, 12, 31),
   'blood_type': 'A-',
   'current_location': (Decimal('33.139177'), Decimal('-106.317532')),
   'name': 'Brandi Smith'},
  {'DOB': datetime.date(2019, 3, 7),
   'blood_type': 'O+',
   'current_location': (Decimal('-80.885105'), Decimal('81.866869')),
   'name': 'Melissa Davis'},
  {'DOB': datetime.date(1979, 6, 2),
   'blood_type': 'O+',
   'current_location': (Decimal('-65.8987285'), Decimal('-171.169046')),
   'name': 'Elizabeth Pearson'},
  {'DOB': datetime.date(1988, 11, 8),
   'blood_type': 'O+',
   'current_location': (Decimal('-63.384062'), Decimal('151.808646')),
   'name': 'Brandi Robinson'},
  {'DOB': datetime.date(2020, 3, 2),
   'blood_type': 'A-',
   'current_location': (Decimal('-87.7525065'), Decimal('-48.040034')),
   'name': 'Steven Thomas'},
  {'DOB': datetime.date(2020, 3, 19),
   'blood_type': 'AB+',
   'current_location': (Decimal('-89.230778'), Decimal('-147.457886')),
   'name': 'Sheena Wilson'},
  {'DOB': datetime.date(1919, 1, 19),
   'blood_type': 'A+',
   'current_location': (Decimal('-81.708510'), Decimal('-50.955892')),
   'name': 'Miss Alyssa Moore MD'},
  {'DOB': datetime.date(1949, 4, 7),
   'blood_type': 'AB-',
   'current_location': (Decimal('66.600110'), Decimal('172.626876')),
   'name': 'Stephanie Marsh'},
  {'DOB': datetime.date(2013, 3, 16),
   'blood_type': 'AB+',
   'current_location': (Decimal('-25.468360'), Decimal('-87.495189')),
   'name': 'Katherine Johnson'},
  {'DOB': datetime.date(1944, 4, 10),
   'blood_type': 'A-',
   'current_location': (Decimal('1.4701985'), Decimal('166.272419')),
   'name': 'Christina Decker'},
  {'DOB': datetime.date(2013, 5, 26),
   'blood_type': 'AB-',
   'current_location': (Decimal('72.991930'), Decimal('82.550793')),
   'name': 'Melanie Allen'},
  {'DOB': datetime.date(1963, 9, 29),
   'blood_type': 'A+',
   'current_location': (Decimal('-67.117779'), Decimal('131.005409')),
   'name': 'Michael Powers'},
  {'DOB': datetime.date(1921, 6, 21),
   'blood_type': 'B-',
   'current_location': (Decimal('-88.295723'), Decimal('-140.695074')),
   'name': 'Mrs. Michelle Scott DVM'},
  {'DOB': datetime.date(1982, 1, 14),
   'blood_type': 'O+',
   'current_location': (Decimal('22.4012995'), Decimal('79.106440')),
   'name': 'Anthony Maldonado'},
  {'DOB': datetime.date(2010, 7, 16),
   'blood_type': 'AB+',
   'current_location': (Decimal('-79.9843245'), Decimal('60.325697')),
   'name': 'Amy Miller'},
  {'DOB': datetime.date(1944, 10, 14),
   'blood_type': 'A+',
   'current_location': (Decimal('-1.114533'), Decimal('100.900772')),
   'name': 'Jennifer Brown'},
  {'DOB': datetime.date(1949, 2, 27),
   'blood_type': 'AB-',
   'current_location': (Decimal('-72.141526'), Decimal('-157.814959')),
   'name': 'Shelly Johnson'},
  {'DOB': datetime.date(1964, 1, 2),
   'blood_type': 'A-',
   'current_location': (Decimal('-33.0531525'), Decimal('40.806664')),
   'name': 'Sonya Lee'},
  {'DOB': datetime.date(2020, 4, 12),
   'blood_type': 'A-',
   'current_location': (Decimal('-69.5269585'), Decimal('-176.119104')),
   'name': 'Matthew Ho Jr.'},
  {'DOB': datetime.date(1958, 8, 10),
   'blood_type': 'O+',
   'current_location': (Decimal('-41.7648235'), Decimal('136.092820')),
   'name': 'Steven Chavez'},
  {'DOB': datetime.date(1941, 7, 24),
   'blood_type': 'A+',
   'current_location': (Decimal('-66.5424795'), Decimal('117.703644')),
   'name': 'Mrs. Mia Miller'},
  {'DOB': datetime.date(2012, 6, 9),
   'blood_type': 'B+',
   'current_location': (Decimal('-88.3348085'), Decimal('28.766819')),
   'name': 'Diamond Lucas'},
  {'DOB': datetime.date(1991, 6, 25),
   'blood_type': 'A-',
   'current_location': (Decimal('-23.968714'), Decimal('-155.162042')),
   'name': 'Andrew Christensen'},
  {'DOB': datetime.date(1937, 4, 3),
   'blood_type': 'O-',
   'current_location': (Decimal('39.5492565'), Decimal('121.547835')),
   'name': 'Vanessa Wise'},
  {'DOB': datetime.date(1989, 11, 28),
   'blood_type': 'AB+',
   'current_location': (Decimal('-29.777090'), Decimal('-12.880494')),
   'name': 'Gina Mccarty'},
  {'DOB': datetime.date(1965, 10, 5),
   'blood_type': 'AB+',
   'current_location': (Decimal('-86.686525'), Decimal('-25.444672')),
   'name': 'Meagan Smith'},
  {'DOB': datetime.date(1995, 3, 6),
   'blood_type': 'A+',
   'current_location': (Decimal('71.7698315'), Decimal('96.509504')),
   'name': 'Nicole Jordan'},
  {'DOB': datetime.date(1923, 3, 5),
   'blood_type': 'B-',
   'current_location': (Decimal('17.437061'), Decimal('96.834826')),
   'name': 'James Dean'},
  {'DOB': datetime.date(1972, 9, 13),
   'blood_type': 'O-',
   'current_location': (Decimal('69.443333'), Decimal('107.141406')),
   'name': 'Danielle Moore'},
  {'DOB': datetime.date(1937, 7, 8),
   'blood_type': 'A+',
   'current_location': (Decimal('29.4846895'), Decimal('-41.224718')),
   'name': 'Randy Bradley'},
  {'DOB': datetime.date(1991, 1, 28),
   'blood_type': 'O-',
   'current_location': (Decimal('-75.080490'), Decimal('15.248677')),
   'name': 'Kylie Singleton'},
  {'DOB': datetime.date(2020, 7, 12),
   'blood_type': 'AB-',
   'current_location': (Decimal('33.022015'), Decimal('-66.083373')),
   'name': 'Chris Thomas'}])